name: Deploy to cPanel
on:
  push:
    branches:
      - main # Puedes especificar la rama desde la que quieres desplegar
jobs:
  deploy:
    name: Deploy to cPanel via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # Directorio local para subir (./ sube todo el proyecto)
          server-dir: ${{ secrets.FTP_PATH }}
          method: ftps
          # dangerous-clean-slate: true //# Esto eliminará archivos en el servidor que no estén en el repositorio
          # exclude: |
          # wp-config.php
          # wp-includes/*
          # wp-admin/*
          # .htaccess
          # wp-content/uploads/*
